config/routes.rb
Roadie::Application.routes.draw do
  resources :sections

  match 'calculate' => 'points#calculate'
  resources :points
  
  root :to => "home#index"
  

end

app/models/point.rb
class Point < ActiveRecord::Base
  belongs_to :section
  validates_presence_of :name, :distance, :section
end

app/models/section.rb
class Section < ActiveRecord::Base
  has_many :points
  validates_presence_of :name, :length
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  
  
  # GET /calculate
  def calculate
    @points = Point.all
    @sections = Section.all
    @errors = Hash.new
    @total_distances = Hash.new
    @total_points_sections = Hash.new
    km, km_c = 0, 0
    
    # loop through all the points
    @points.each do |point|
    
      # calculate the ground elevation if none is already present
      if point.elevation.nil?
        
        # calculate and round to two decimals
        if point.d1 and point.d2
          elev = point.d1 / point.d2
          elev = elev + point.height - 1 
          elev = (elev * 10**2).round.to_f / 10**2
          point.elevation = elev
        end
      end
      
        
      
        # calculate the current kilometric position
        
        km += point.distance
        point.kilometric_position = '0+' + km.to_s    
        
       
        # calculate the corrected kilometric position
        
        error = point.distance_corrected - point.distance
        km_c = km
        km_c += error
        point.kilometric_position_corrected = '0+' + km_c.to_s
        
        
        # save to the database      
        point.save
    end
    
    


    @sections.each_with_index do |section, sindex|
      
      section_points_number = section.points.count - 1
      section_length = section.length
      total_distance = 0
      
      # calculate total distance
      section.points.each do |point|
        total_distance += point.distance
      end
      
      # save total distances for later use
      @total_distances[sindex] = total_distance
      
      # calculate total error for a section
      total_error = total_distance - section_length
      
      # calculate error for each section
      error = total_error / section_points_number
      error = (error * 10**2).round.to_f / 10**2
            
      # save errors for later use
      @errors[sindex] = error      
      
      # calculate total number of points
      total_points_calc = section.points.count - 1
      
      # save total number of points for later use
      @total_points_sections[sindex] = total_points_calc
      
      section.points.each_with_index do |point, index| 
          
          if point.distance_corrected.nil?      
    	        	    
    	      # construct final variable
      	    point.distance_corrected = point.distance + error
      	    
      	    # exclude starting and final points for error calculation    	      
    	      if index.eql? 0 or point.name.eql? "A" or point.name.eql? "B"
    	        point.distance_correcteded = point.distance
    	      end
    	      
    	      # save to database
      	    point.save
      	    
      	    
  	      end
    	  end   	  	  
  	    
    end
    
    # return us to the index page
    # redirect_to(points_url, :notice => 'Elevation calculated')
  end
  
  # GET /points
  # GET /points.xml
  def index
    @points = Point.all
   
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @points }
    end
  end

  # GET /points/1
  # GET /points/1.xml
  def show
    @point = Point.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @point }
    end
  end

  # GET /points/new
  # GET /points/new.xml
  def new
    @point = Point.new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @point }
    end
  end

  # GET /points/1/edit
  def edit
    @point = Point.find(params[:id])
    @sections = Section.all
  end

  # POST /points
  # POST /points.xml
  def create
    @point = Point.new(params[:point])

    respond_to do |format|
      if @point.save
        format.html { redirect_to(@point, :notice => 'Point added') }
        format.xml  { render :xml => @point, :status => :created, :location => @point }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @point.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /points/1
  # PUT /points/1.xml
  def update
    @point = Point.find(params[:id])
    
    respond_to do |format|
      if @point.update_attributes(params[:point])
        format.html { redirect_to(@point, :notice => 'Point was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @point.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /points/1
  # DELETE /points/1.xml
  def destroy
    @point = Point.find(params[:id])
    @point.destroy

    respond_to do |format|
      format.html { redirect_to(points_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  # GET /sections
  # GET /sections.xml
  def index
    @sections = Section.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @sections }
    end
  end

  # GET /sections/1
  # GET /sections/1.xml
  def show
    @section = Section.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @section }
    end
  end

  # GET /sections/new
  # GET /sections/new.xml
  def new
    @section = Section.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @section }
    end
  end

  # GET /sections/1/edit
  def edit
    @section = Section.find(params[:id])
  end

  # POST /sections
  # POST /sections.xml
  def create
    @section = Section.new(params[:section])

    respond_to do |format|
      if @section.save
        format.html { redirect_to(@section, :notice => 'Section was successfully created.') }
        format.xml  { render :xml => @section, :status => :created, :location => @section }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @section.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sections/1
  # PUT /sections/1.xml
  def update
    @section = Section.find(params[:id])

    respond_to do |format|
      if @section.update_attributes(params[:section])
        format.html { redirect_to(@section, :notice => 'Section was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @section.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.xml
  def destroy
    @section = Section.find(params[:id])
    @section.destroy

    respond_to do |format|
      format.html { redirect_to(sections_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/home/index.html.erb
<h1>Hello there!</h1>

<p>Roadie currently supports the following actions</p>

<ul>
	<li><%= link_to "Add sections", new_section_path %></li>
	<li><%= link_to "Add points", new_point_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Roadie</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<%= yield %>
<hr>
<%= link_to "View Sections", { :controller => "sections", :action => "index" } %> | <%= link_to "View Points", { :controller => "points", :action => "index" } %>
</body>
</html>

app/views/points/_error.erb
<% section.points.each_with_index do |point, index| %>
		<%= 				
		 # if this isn't the first section and the point.distance is 0
      sindex != 0 and point.distance == 0 ? point.distance = nil : point.distance = point.distance

		 # add a + after each point that isn't the last
		 index != @total_points_calc ? point.distance.to_s + ' +' : point.distance
		%>
<% end %>

app/views/points/_form.html.erb
<%= form_for(@point) do |f| %>
  <% if @point.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@point.errors.count, "error") %> prohibited this point from being saved:</h2>

      <ul>
      <% @point.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :section %><br />
  	<%= f.collection_select(:section_id, Section.all, :id, :name, :prompt => 'Select a Section') %>
  </div>

  <div class="field">
    <%= f.label :distance %><br />
    <%= f.text_field :distance %>
  </div>
	<div class="field">
    <%= f.label :distance_corrected %><br />
    <%= f.text_field :distance_corrected %>
  </div>
	<div class="field">
    <%= f.label :kilometric_position %><br />
    <%= f.text_field :kilometric_position %>
  </div>
	<div class="field">
    <%= f.label :kilometric_position_corrected %><br />
    <%= f.text_field :kilometric_position_corrected %>
  </div>
  <div class="field">
    <%= f.label :elevation %><br />
    <%= f.text_field :elevation %>
  </div>
  <div class="field">
    <%= f.label :height %><br />
    <%= f.text_field :height %>
  </div>
  <div class="field">
    <%= f.label :d1 %><br />
    <%= f.text_field :d1 %>
  </div>
  <div class="field">
    <%= f.label :d2 %><br />
    <%= f.text_field :d2 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/points/_point.erb
<tr class="<%= cycle("even", "odd") %>">
  <td><%= point.name %></td>
	<td><%= point.section_id %></td>
  <td><%= point.distance %></td>
	<td><%= point.distance_corrected %></td>
	<td><%= point.kilometric_position %></td>
	<td><%= point.kilometric_position_corrected %></td>
  <td><%= point.elevation %></td>
	<td><%= point.height %></td>
  <td><%= point.d1 %></td>
  <td><%= point.d2 %></td>
  <td><%= link_to 'Show', point %></td>
  <td><%= link_to 'Edit', edit_point_path(point) %></td>
  <td><%= link_to 'Destroy', point, :confirm => 'Are you sure?', :method => :delete %></td>
</tr>

app/views/points/calculate.html.erb
<h1>Point calculation</h1>
<%=	javascript_include_tag "http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" %>

<h2>Output for error calculations</h2>

<% @sections.each_with_index do |section, sindex| %>

	<% # Retrieve our values
	total_distance = @total_distances[sindex]
	@total_points_calc = @total_points_sections[sindex]
	total_points = section.points.count
	error = @errors[sindex]
	%>
	
	<h3>Section	<i><%= section.name %></i></h3>
	<hr>
	<p>
		\( \Sigma d_{<%= section.name %>} = <%= section.name %> \)
	</p>
	<p>
		\( \Sigma d_{<%= section.name %>}= \) <%= render :partial => 'points/error', :locals => {:section => section, :sindex => sindex} %> = <%= total_distance %>			
	</p>
	<p>
		\( <%= section.name %>= \) <%= section.length %>
	</p>
	<p>e = \( \frac{<%= total_distance %> - <%= section.length %>}{<%= @total_points_calc %>} \) = <%= error %></p>
<% end %>

app/views/points/edit.html.erb
<h1>Editing point</h1>

<%= render 'form' %>

<%= link_to 'Show', @point %> |
<%= link_to 'Back', points_path %>

app/views/points/index.html.erb
<h1>Listing points</h1>
<table>
  <tr>
    <th>Name</th>
		<th>Section</th>
    <th>Distance</th>
		<th>Distance Corrected</th>
		<th>Kilometric position</th>
		<th>Kilometric position corrected</th>
    <th>Elevation</th>
		<th>Height</th>
    <th>D1</th>
    <th>D2</th>
    <th></th>
    <th></th>
		<th></th>
  </tr>
<%= render @points %>
</table>

<br />

<%= link_to 'New Point', new_point_path %>
<%= link_to 'Calculate', :controller => "points", :action => "calculate" %>

app/views/points/new.html.erb
<h1>New point</h1>

<%= render 'form' %>

<%= link_to 'Back', points_path %>

app/views/points/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @point.name %>
</p>

<p>
  <b>Distance:</b>
  <%= @point.distance %>
</p>

<p>
  <b>Kilometric position:</b>
  <%= @point.kilometric_position %>
</p>

<p>
  <b>Elevation:</b>
  <%= @point.elevation %>
</p>

<p>
  <b>Height:</b>
  <%= @point.height %>
</p>

<p>
  <b>D1:</b>
  <%= @point.d1 %>
</p>

<p>
  <b>D2:</b>
  <%= @point.d2 %>
</p>

<%= link_to 'Edit', edit_point_path(@point) %> |
<%= link_to 'Add another point', new_point_path %> |
<%= link_to 'Back', points_path %>

app/views/sections/_form.html.erb
<%= form_for(@section) do |f| %>
  <% if @section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% @section.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :length %><br />
    <%= f.text_field :length %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sections/edit.html.erb
<h1>Editing section</h1>

<%= render 'form' %>

<%= link_to 'Show', @section %> |
<%= link_to 'Back', sections_path %>

app/views/sections/index.html.erb
<h1>Listing sections</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Length</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sections.each do |section| %>
  <tr>
    <td><%= section.name %></td>
    <td><%= section.length %></td>
    <td><%= link_to 'Show', section %></td>
    <td><%= link_to 'Edit', edit_section_path(section) %></td>
    <td><%= link_to 'Destroy', section, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Section', new_section_path %>

app/views/sections/new.html.erb
<h1>New section</h1>

<%= render 'form' %>

<%= link_to 'Back', sections_path %>

app/views/sections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @section.name %>
</p>

<p>
  <b>Length:</b>
  <%= @section.length %>
</p>


<%= link_to 'Edit', edit_section_path(@section) %> |
<%= link_to 'Back', sections_path %>